version: '3.8'
services:
  db:
    restart: always
    image: postgres:13
    env_file: ./.env
    volumes:
      - db_value:/var/lib/postgresql/data/

  backend:
    image: kokorinpetr/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/foodgram/collected_static/
      - media_value:/app/foodgram/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: kokorinpetr/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend

volumes:
  static_value:
  media_value:
  db_value: